[package]
name = "twoD_physics"
version = "0.1.0"
authors = ["sclolus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston2d-graphics = "0.40.0"
piston_window = "*"
piston = "0.53.0"
rand = "*"